#!/usr/bin/env bash

set -euo pipefail
export CACHE_ROOT=/mnt/crate-cache
mkdir -p "$CACHE_ROOT"

# I wish this would cut it, but somewhere along the line, the proxy configuration is lost.
#exec java -Djava.net.useSystemProxies=true -jar /opt/ccp.jar -m puppetlabs.crates-caching-proxy.core

mkdir -p ~/.proxychains
if test -z ${PROXYCHAINS+x} && test -n ${http_proxy+x}; then
	PROXYCHAINS="$(sed <<<"$http_proxy" -rn 's#(https?)://(((.*):(.*)@)?(.+)):([0-9]+)/?$#\1 \6 \7 \4 \5#p')"
	if test -z ${PROXYCHAINS:+x}; then
		echo "WARNING: http_proxy is set but PROXYCHAINS couldn't be configured" 1>&2
	fi
fi
if test -n ${PROXYCHAINS:+x}; then
	echo "
		strict_chain
		proxy_dns
		tcp_read_time_out 24000
		tcp_connect_time_out 15000
		quiet_mode
		[ProxyList]
		$PROXYCHAINS
	" | sed -r 's/^[ \t]*//' >~/.proxychains/proxychains.conf
	exec proxychains4 java -jar /opt/ccp.jar -m puppetlabs.crates-caching-proxy.core
else
	exec java -jar /opt/ccp.jar -m puppetlabs.crates-caching-proxy.core
fi
